name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
      
      - name: Run tests
        run: |
          uv run pytest tests/ -v
      
      - name: Run linting
        run: |
          uv run ruff check .
          uv run black --check .
      
      - name: Test package build
        run: |
          uv build
          # Test that the package can be installed
          uv pip install dist/*.whl
          # Test that the CLI works
          uv run umbrix-mcp --help || true